---
- name: Grading playbook for SCENARIO_CANDLEPIN
  hosts: satellite
  gather_facts: no
  become: true
  tasks:
        - name: Detecting health
          ansible.builtin.command: bash -c "hammer --output=json ping  | jq -r '.[].candlepin.Status'"
          register: health

        - name: In case of success
          ansible.builtin.debug:
            msg: " Success!! Your alphanumeric code for completion is CANDLEPIN26"
          when: health.stdout == 'ok'

        - name: In case of failure
          ansible.builtin.debug:
            msg: "Not all services are up, please try again"
          when: health.stdout != 'ok'

