---
# tasks file for breakfix0
- name: Set initial facts
  ansible.builtin.set_fact:
    satellite_hostname: "{{ ansible_fqdn }}"

- name: Read credentials
  ansible.builtin.slurp:
      path: /root/.hammer/cli.modules.d/foreman.yml  
  register: slurp

- name: Set credentials
  set_fact:
        password: "{{ (slurp.content | b64decode | from_yaml)[':foreman'][':password'] }}"
        username: "{{ (slurp.content | b64decode | from_yaml)[':foreman'][':username'] }}"


- name: Check satellite health via hammer
  ansible.builtin.command: bash -c "hammer --output=json ping  | jq -r '.[].candlepin.Status'"
  register: health

- name: Stop all Satellite services
  ansible.builtin.command: bash -c "satellite-maintain service stop"
  changed_when: true
  when: health.stdout != 'FAIL'
  register: stop_services

- debug: var=stop_services

- name: Set group 'root' on /etc/tomcat
  ansible.builtin.file:
        path: /etc/tomcat
        group: root
        recurse: true
        state: directory
  when: health.stdout != 'FAIL'

- name: Set group 'root' on candlepin.conf
  ansible.builtin.file:
        path: /etc/candlepin/candlepin.conf
        group: root
        state: file
  when: health.stdout != 'FAIL'

- name: Set ownership on /var/log/candlepin
  ansible.builtin.file:
        path: /var/log/candlepin
        owner: root
        group: root
        recurse: true
        state: directory
  when: health.stdout != 'FAIL'

- name: Set permissions on /var/log/candlepin
  ansible.builtin.command: bash -c "chmod 600 -R /var/log/candlepin"
  changed_when: true
  when: health.stdout != 'FAIL'


- name: Start Satellite services
  ansible.builtin.command: bash -c "satellite-maintain service start"
  changed_when: true
  failed_when: false
  when: health.stdout != 'FAIL'

- name: Verify tomcat service is in 'failed' state
  ansible.builtin.command: bash -c "systemctl is-failed tomcat"
  register: tomcat_stat
  changed_when: false

- name: Tomcat is in 'failed' state as expected
  ansible.builtin.debug:
        msg: "Tomcat status: {{ tomcat_stat.stdout }}. It is broken now."
  when: tomcat_stat.rc == 0
